# CI/CD DevOps 2025 — Pipeline principal
name: CI devops 2025

on:
  push:
    branches: [ main, develop ]


jobs:
  # --- JOB 1 : TEST BACKEND (Maven) ---
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build and test with Maven
        run: mvn -B -ntp clean verify --file simple-api/pom.xml

  # --- JOB 2 : BUILD & (CONDITIONALLY) PUSH DOCKER IMAGES ---
  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api
          file: ./simple-api/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./database
          file: ./database/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./http-server
          file: ./http-server/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}

# --- SonarCloud analysis ---
      # --- SonarCloud analysis ---
      - name: SonarCloud Scan (Maven)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # pour décorer les PR
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}     # ton token SonarCloud (secret)
        run: >
          mvn -B verify sonar:sonar
          -Dsonar.projectKey=Moieuh_tp-devops-correction-docker
          -Dsonar.organization=moieuh
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          --file ./simple-api/pom.xml

