  # --- JOB 2 : BUILDER & (éventuellement) PUSHER LES IMAGES DOCKER ---
  build-and-push-docker-image:
    needs: test-backend     # garantit que les tests passent avant de builder/pusher
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # (Optionnel mais recommandé pour multi-arch) :
      # - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      # Se connecter à Docker Hub (on ne pousse que sur main)
      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Backend (simple-api)
      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api
          file: ./simple-api/Dockerfile
          # Tag en minuscules !
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          # Build pour toutes les branches, push seulement sur main
          push: ${{ github.ref == 'refs/heads/main' }}

      # Database
      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./database
          file: ./database/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      # HTTPD
      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./httpd
          file: ./httpd/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}
